title: Myron Bañez
logo: "/images/myb.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <a href="https://www.linkedin.com/in/myronbanez/">LinkedIn</a> | <a href="https://www.mjbanez.squarespace.com">Website</a> | <a href="https://github.com/myronbanez">Github</a>
 <br><br>
  Master of City Planning Candidate @ University of Pennsylvania
 <br><br>
  I am interested in using geospatial data science to find solutions in transportation, economic development, public space, and the environment. 

theme: jekyll-theme-minimal
