title: Myron Bañez
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Master of City Planning @ University of Pennsylvania's Weitzman School of Design 
  <br><br>
  In love with maps, data, ethnic enclaves, and fitness!  
  <br><br>
  <a href="https://www.linkedin.com/in/myronbanez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
