title: Myron Bañez
logo: "/images/My.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <a href="https://www.linkedin.com/in/myronbanez/">LinkedIn</a> | <a href="https://www.mjbanez.squarespace.com">Website</a> | <a href="https://github.com/myronbanez">Github</a>
 <br><br>
  Master of City Planning Candidate @ University of Pennsylvania
 <br><br>
  Constantly thinking about geospatial analytics, city planning, transportation, small businesses, placemaking, and maps.
 <br><br>
  [Geospatial Analysis in R](https://github.com/myronbanez/Portfolio/blob/master/index.md#geospatial-data-analysis-in-r)
  [Geographic Information Systems](https://github.com/myronbanez/Portfolio/blob/master/index.md#geographic-information-systems)
  
theme: jekyll-theme-minimal
