title: Myron Bañez
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <a href="https://www.linkedin.com/in/myronbanez/">LinkedIn</a> | <a href="https://www.mjbanez.squarespace.com">Website</a> | <a href="https://github.com/myronbanez">Github</a>
 <br><br>
  Master of City Planning @ UPenn Weitzman School of Design 
  <br><br>
  Constantly thinking about geospatial analytics, immigrant/ethnic enclaves, placemaking, and small businesses.  
  <br><br>
  I enjoy maps, fitness, and learning about different cultures!
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
