title: Myron Bañez
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <a href="https://www.linkedin.com/in/myronbanez/">LinkedIn</a> | <a href="https://www.mjbanez.squarespace.com">Website</a>
 <br><br>
  Master of City Planning @ University of Pennsylvania's Weitzman School of Design 
  <br><br>
  My interests can be found in community economic development, geospatial analytics, immigrant communities and ethnic enclaves, placemaking, and small businesses.  
  <br><br>
  I enjoy maps, fitness, and learning about different cultures!
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
